# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(668, 520)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(232, 232, 232)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_tb = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.chat_tb.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(99, 185, 149), stop:1 rgba(255, 255, 255, 255));\n"
"border: none;\n"
"    outline: none;")
        self.chat_tb.setReadOnly(True)
        self.chat_tb.setObjectName("chat_tb")
        self.verticalLayout.addWidget(self.chat_tb)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_file_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.add_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_file_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.add_file_btn.setToolTipDuration(-1)
        self.add_file_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"outline: none;")
        self.add_file_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("interface/ui_and_svg/add_file_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_file_btn.setIcon(icon)
        self.add_file_btn.setObjectName("add_file_btn")
        self.horizontalLayout_2.addWidget(self.add_file_btn)
        self.message_tb = QtWidgets.QLineEdit(self.centralwidget)
        self.message_tb.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_tb.setFont(font)
        self.message_tb.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"    outline: none;")
        self.message_tb.setText("")
        self.message_tb.setObjectName("message_tb")
        self.horizontalLayout_2.addWidget(self.message_tb)
        self.send_msg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_msg_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.send_msg_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_msg_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"    outline: none;")
        self.send_msg_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("interface/ui_and_svg/send_message_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_msg_btn.setIcon(icon1)
        self.send_msg_btn.setObjectName("send_msg_btn")
        self.horizontalLayout_2.addWidget(self.send_msg_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.file_lbl.setFont(font)
        self.file_lbl.setStyleSheet("font: 10pt \"Sitka\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(44, 102, 110)")
        self.file_lbl.setObjectName("file_lbl")
        self.horizontalLayout.addWidget(self.file_lbl)
        self.remove_file_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_file_btn.sizePolicy().hasHeightForWidth())
        self.remove_file_btn.setSizePolicy(sizePolicy)
        self.remove_file_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.remove_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_file_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.remove_file_btn.setToolTipDuration(-1)
        self.remove_file_btn.setStyleSheet("\n"
"border: none;\n"
"outline: none;")
        self.remove_file_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("interface/ui_and_svg/remove_file_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_file_btn.setIcon(icon2)
        self.remove_file_btn.setIconSize(QtCore.QSize(15, 15))
        self.remove_file_btn.setObjectName("remove_file_btn")
        self.horizontalLayout.addWidget(self.remove_file_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Чат"))
        self.file_lbl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Нет прикрепленного файла</p></body></html>"))
