# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(322, 126)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"Sitka\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(44, 102, 110)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.progress = QtWidgets.QProgressBar(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy)
        self.progress.setMinimumSize(QtCore.QSize(0, 30))
        self.progress.setStyleSheet("QProgressBar{\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    color: rgb(7, 57, 60);\n"
"    border-radius: 10px;\n"
"    border-style: solid; \n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(99, 185, 149), stop:1 rgb(213, 255, 222));\n"
"}")
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.verticalLayout.addWidget(self.progress)
        self.cancel_loading_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_loading_btn.sizePolicy().hasHeightForWidth())
        self.cancel_loading_btn.setSizePolicy(sizePolicy)
        self.cancel_loading_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.cancel_loading_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cancel_loading_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cancel_loading_btn.setStyleSheet("background-color: rgb(194, 232, 202);\n"
"border: none;\n"
"outline: none;\n"
"border-radius: 10px;\n"
"font: 8pt \"Sitka\";\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(44, 102, 110)\n"
"\n"
"")
        self.cancel_loading_btn.setObjectName("cancel_loading_btn")
        self.verticalLayout.addWidget(self.cancel_loading_btn, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Отправка файла"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">Загрузка файла</p></body></html>"))
        self.cancel_loading_btn.setText(_translate("Form", "Отмена"))
